name: ci

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Read envirnoment variables
        run: env
      - name: Read current working directory
        run: pwd
      - name: Read current working directory content
        run: ls -la
      - name: Build mta
        run: |
          docker run -t --rm -v "$(pwd):/project" devxci/mbtci:latest mbt build -p=cf